name: Release Charts

on:
  release:
    types:
      - created

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create issue
        id: create_issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CSI_WF_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/release-template.md
          assignees: misanthropicat
        if: startsWith(github.ref, 'refs/tags/')

      - name: Parse issue body
        uses: peter-murray/issue-body-parser-action@v1
        id: parse_issue
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ steps.create_issue.outputs.number }}
          payload: yaml

      - name: Trigger release workflow in csi-baremetal-operator repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release Charts
          repo: misanthropicat/csi-baremetal-operator
          token: ${{ secrets.CSI_WF_TOKEN }}
          ref: ${{ github.event.release.target_commitish }}
          inputs: |
            { "issue_number": "${{ steps.create_issue.outputs.number }}",
              "csi_version": "${{ steps.parse_issue.payload.csi_version }}",
              "csi_operator_version": "${{ steps.parse_issue.payload.csi_operator_version }}"
              "release_tag": "${{ github.event.release.tag_name }}" }
        if: startsWith(github.ref, 'refs/tags/')

