name: Release Charts

on:
  release:
    types:
      - created

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Create issue
      #   id: create_issue
      #   uses: JasonEtco/create-an-issue@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CSI_WF_TOKEN }}
      #   with:
      #     filename: .github/ISSUE_TEMPLATE/release-template.md
      #     assignees: misanthropicat
      #   if: startsWith(github.ref, 'refs/tags/')

      - id: split_description
        uses: jungwinter/split@v2
        with:
          msg: ${{ github.event.release.body }}
          separator: '\n'

      - id: parse_first
        uses: jungwinter/split@v2
        with:
          msg: ${{ steps.split_description.outputs._0 }}
          separator: ': '

      - id: parse_second
        uses: jungwinter/split@v2
        with:
          msg: ${{ steps.split_description.outputs._1 }}
          separator: ': '

      - name: Set versions
        id: versions
        run: |
          echo "::set-output name=${{ steps.parse_first.outputs._0 }}::${{ steps.parse_first.outputs._1 }}"
          echo "::set-output name=${{ steps.parse_second.outputs._0 }}::${{ steps.parse_second.outputs._1 }}"

      # - name: Parse issue body
      #   uses: peter-murray/issue-body-parser-action@v1
      #   id: parse_issue
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     issue_id: 4
      #     payload: yaml

      - name: Trigger release workflow in csi-baremetal-operator repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release Charts
          repo: misanthropicat/csi-baremetal-operator
          token: ${{ secrets.CSI_WF_TOKEN }}
          ref: ${{ github.event.release.target_commitish }}
          inputs: |
            { "issue_number": "${{ steps.create_issue.outputs.number }}",
              "csi_version": "${{ steps.versions.csi_version }}",
              "csi_operator_version": "${{ steps.versions.csi_operator_version }}",
              "release_tag": "${{ github.event.release.tag_name }}" }
        if: startsWith(github.ref, 'refs/tags/')

